"""Adding user_id to TotalBudget

Revision ID: 03b6205e5636
Revises: a98ab01363ca
Create Date: 2025-04-02 14:49:30.202099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b6205e5636'
down_revision = 'a98ab01363ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table('total_budget', schema=None) as batch_op:
    batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
    batch_op.create_foreign_key('fk_totalbudget_user', 'users', ['user_id'], ['id'])  # Fix


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('total_budget', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
